algoritmo "semnome"
// Função :
// Autor :
// Data : 25/04/2022
// Seção de Declarações
var
qntminima, qntmaxima, estoquemedio: real


inicio
// Dados de Entrada

escreval("Digite a quantidade minima de peças")
leia(qntminima)
escreval("Digite a quantidade maxima de peças:")
leia (qntmaxima)
//processamento
estoquemedio <-(qntmaxima)
estoquemedio <-(qntminima+qntmaxima)/2
//Dados de Saida
escreval ("O estoque medio é:",estoquemedio)




fimalgoritmo
